//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faculty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public string studname { get; set; }
        public string passwordd { get; set; }
        public string email { get; set; }
        public string addresss { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> DepID { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
